export const OPEN_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] OPEN_ADVANCED_SEARCH";
export const CLOSE_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] CLOSE_ADVANCED_SEARCH";
export const TOGGLE_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] TOGGLE_ADVANCED_SEARCH";




export const MOVIE_GENRE_SEARCH_CHANGE = "[MOVIE_DB][ADVANCED_SEARCH] MOVIE_GENRE_SEARCH_CHANGE";
export const MOVIE_ADULT_SEARCH_CHANGE = "[MOVIE_DB][ADVANCED_SEARCH] MOVIE_ADULT_SEARCH_CHANGE,";
export const MOVIE_TITLE_SEARCH_CHANGE = "[MOVIE_DB][ADVANCED_SEARCH] MOVIE_TITLE_SEARCH_CHANGE";
export const MOVIE_OVERVIEW_SEARCH_CHANGE = "[MOVIE_DB][ADVANCED_SEARCH] MOVIE_OVERVIEW_SEARCH_CHANGE";
export const DO_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] DO_ADVANCED_SEARCH";
export const MOVIE_SAVE_SEARCH_CONFIG = "[MOVIE_DB][ADVANCED_SEARCH] MOVIE_SAVE_SEARCH_CONFIG";