export const OPEN_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] OPEN_ADVANCED_SEARCH";
export const CLOSE_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] CLOSE_ADVANCED_SEARCH";
export const TOGGLE_ADVANCED_SEARCH = "[MOVIE_DB][ADVANCED_SEARCH] TOGGLE_ADVANCED_SEARCH";