export const CARD_CLICK = '[MOVIE_DB][DASHBOARD] CARD_CLICK';
export const ADD_MOVIE_CLICK = '[MOVIE_DB][DASHBOARD] ADD_MOVIE_CLICK';
export const ABOUT_CLICK = '[MOVIE_DB][DASHBOARD] ABOUT_CLICK';
export const PRICING_CLICK = '[MOVIE_DB][DASHBOARD] PRICING_CLICK';
export const BLOG_CLICK = '[MOVIE_DB][DASHBOARD] BLOG_CLICK';

export const FORM_ADD_MOVIE = '[MOVIE_DB][FORM] FORM_ADD_MOVIE';
export const FORM_CANCEL_MOVIE = '[MOVIE_DB][FORM] FORM_CANCEL_MOVIE';
export const MOVIE_DATA_BACKEND = '[MOVIE_DB][DATA] MOVIE_DATA_BACKEND';

export const GET_MOVIE_DATA = '[MOVIE_DB][DATA] GET_MOVIE_DATA';