export const MENU_CLICK = '[MOVIE_DB][SIDEBAR] MENU_CLICK';
export const MENU_MOVIE_CLICK = '[MOVIE_DB][SIDEBAR] MENU_MOVIE_CLICK';
export const MENU_SHOW_CLICK = '[MOVIE_DB][SIDEBAR] MENU_SHOW_CLICK';
export const MENU_LIBRARY_CLICK = '[MOVIE_DB][SIDEBAR] MENU_LIBRARY_CLICK';
export const MENU_SUPPORT_CLICK = '[MOVIE_DB][SIDEBAR] MENU_SUPPORT_CLICK';